server:
  port: 8080

spring:
  application:
    name: obelix-webshop

quarry:
  base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        # include the metrics for prometheus
        include: health, info, prometheus, metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
